export const MANUAL_SCORING_BATCH_SIZE = 50;
export const SCORING_RUN_CHILD_BATCH_SIZE = 40;
export const MAX_SCORING_RUN_JOBS = 2_000;
export const MAX_SCORING_RUN_EXCHANGE_BYTES = 64 * 1024 * 1024;

export const SCORING_IMPORT_TRANSACTION_TIMEOUT_MS = 60_000;
