import assert from 'node:assert/strict';
import test from 'node:test';

import {
  employerFeedFamily,
  isUnusableDescription,
  judgeSameJob,
  sameJobAnchorCity,
  sameJobLocationRelation,
  sameJobTextAgrees,
  sameJobTitleKey,
  type SameJobSubject,
} from '../sameJobMatch';

function words(seed: string, count: number): string {
  return Array.from({ length: count }, (_, index) => `${seed}${(index * 7919) % 1009}`).join(' ');
}

const JD = words('duty', 280);
/** How aggregators reprint a posting: markup, lost line breaks, a publisher footer. */
const REPRINT = `<div><p>${JD.split(' ').slice(0, 140).join(' ')}</p><p>${JD.split(' ').slice(140).join(' ')}</p></div>\nOriginally posted on Himalayas`;
/** Another requisition from the same employer: shared boilerplate, a different role section. */
const BOILERPLATE = words('about', 150);
const REQ_A = `${BOILERPLATE} ${words('reqa', 130)}`;
const REQ_B = `${BOILERPLATE} ${words('reqb', 130)}`;
const CLOUDFRONT = `Title: The request could not be satisfied\nURL Source: https://www.adzuna.com/land/ad/1\nWarning: Target URL returned error 403: Forbidden\n# 403 ERROR ${words('cf', 200)} Generated by cloudfront (CloudFront)`;

let nextId = 0;
function card(overrides: Partial<SameJobSubject>): SameJobSubject {
  nextId += 1;
  return {
    id: `job-${nextId}`, title: 'Account Manager', company: 'Acme', location: 'Minneapolis, MN',
    description: JD, source: 'Himalayas', ...overrides,
  };
}

function same(left: Partial<SameJobSubject>, right: Partial<SameJobSubject>) {
  return judgeSameJob(card(left), card(right));
}

// Every label pair below is a real production pair from the 2026-09-25 census.

test('the copies Joseph kept seeing twice are one job', () => {
  const pairs: Array<[Partial<SameJobSubject>, Partial<SameJobSubject>]> = [
    [{ source: 'Himalayas', company: 'Calibrate', title: 'Senior Customer Success Manager', location: 'United States' },
      { source: 'ATS-rippling', company: 'Calibrate Health, Inc.', title: 'Senior Customer Success Manager', location: 'Remote (United States)' }],
    [{ source: 'Himalayas', company: 'J.D. Power', title: 'Manager, Customer Success - Digital Retail', location: 'United States' },
      { source: 'ATS-workday', company: 'JD Power', title: 'Manager, Customer Success - Digital Retail', location: 'Remote USA' }],
    [{ source: 'LinkedIn (Apify)', company: 'Arctic Wolf', title: 'Account Manager - MSP', location: 'Eden Prairie, MN' },
      { source: 'ATS-workday', company: 'Arctic Wolf Networks, Inc.', title: 'Account Manager - MSP', location: 'Eden Prairie, MN, USA' }],
    [{ source: 'Himalayas', company: 'Zillow Group', title: 'Manager, Customer Success, Strategic', location: 'United States' },
      { source: 'ATS-workday', company: 'ZINC Zillow, Inc.', title: 'Manager, Customer Success, Strategic', location: 'Remote-USA' }],
    [{ source: 'Himalayas', company: 'Progressive Leasing', title: 'Account Manager, Wireless', location: 'United States' },
      { source: 'ATS-workday', company: 'Progleasing', title: 'Account Manager, Wireless', location: 'Remote' }],
    [{ source: 'careerforce', company: 'U.S. Bank', title: 'P-040289 Client Executive', location: 'Minneapolis, MN' },
      { source: 'ATS-workday', company: 'Elavon, Inc.', title: 'P-040289 Client Executive', location: 'Atlanta, GA; Denver, CO; Knoxville, TN; Minneapolis, MN' }],
    [{ source: 'Adzuna', company: 'HP Inc.', title: 'Partner Business Manager', location: 'Saint Paul, MN' },
      { source: 'ATS-workday', company: 'Hp', title: 'Partner Business Manager', location: 'All Cities, Minnesota, United States of America; All Cities, Iowa, United States of America' }],
    [{ source: 'SerpApi', company: 'Techtronic Industries - TTI', title: 'Field Sales &amp; Marketing Representative', location: 'Minneapolis, MN' },
      { source: 'LinkedIn', company: 'Techtronic Industries - TTI', title: 'Field Sales & Marketing Representative - Minneapolis, MN', location: 'Minneapolis, Minnesota, United States' }],
    [{ source: 'JSearch', company: 'Henkel', title: 'Senior Territory Sales Manager - Building Industry job at Henkel in US National', location: 'Unknown Location' },
      { source: 'Adzuna', company: 'Henkel', title: 'Senior Territory Sales Manager - Building Industry', location: 'Chanhassen, Carver County' }],
  ];
  for (const [left, right] of pairs) {
    const evidence = same({ ...left, description: JD }, { ...right, description: REPRINT });
    assert.ok(evidence, `${left.company} / ${right.company}`);
    assert.equal(evidence.rule, 'description');
    assert.ok(evidence.containment! >= 0.99);
  }
});

test('requisitions that share an employer\'s boilerplate stay apart', () => {
  // Samsara posted five Enterprise CSM requisitions; the Himalayas copy of one
  // shared 58% of its text with the requisition Joseph applied to.
  assert.equal(same(
    { source: 'Himalayas', company: 'Samsara', title: 'Enterprise Customer Success Manager', location: 'United States', description: REQ_A },
    { source: 'ATS-greenhouse', company: 'samsara', title: 'Enterprise Customer Success Manager', location: 'Remote - US', description: REQ_B },
  ), null);
  assert.equal(sameJobTextAgrees(card({ description: REQ_A }), card({ description: REQ_B })), false);
});

test('territory postings with the same text stay apart', () => {
  for (const [left, right] of [
    ['Minneapolis, MN', 'Sioux City, Woodbury County'],
    ['Savage, Minnesota', 'Stewartville, Minnesota'],
    // Different suburbs of one metro are different territories when merging.
    ['Shakopee, MN', 'Maple Grove, Hennepin County'],
    // Adzuna drops the state: this Bloomington is in Illinois.
    ['Bloomington, McLean County', 'Saint Paul, Ramsey County'],
  ]) {
    assert.equal(sameJobLocationRelation(left, right), 'conflict', `${left} / ${right}`);
    assert.equal(same({ location: left, source: 'Adzuna' }, { location: right, source: 'JSearch' }), null, `${left} / ${right}`);
  }
  // Remote or national never contradicts a place, and one city written two ways is one city.
  assert.notEqual(sameJobLocationRelation('United States', 'Eden Prairie, MN'), 'conflict');
  assert.notEqual(sameJobLocationRelation('Minneapolis, Hennepin County', 'Minneapolis, MN'), 'conflict');
  assert.notEqual(sameJobLocationRelation('All Cities, Minnesota, United States of America', 'Saint Paul, MN'), 'conflict');
});

test('titles that differ by a word are different jobs', () => {
  for (const [left, right] of [
    ['Sr. Partner Manager - AWS', 'Sr. Partner Manager – System Integrators'],
    ['Provider Relations Specialist- TX', 'Provider Relations Specialist- West MN'],
    ['District Manager(07371) - 3260 Brookdale Dr N', 'District Manager(01901) - 215 Oak St SE'],
    ['Account Manager, Retail', 'Sr Account Manager, Retail'],
    ['Customer Success Manager', 'Customer Success Manager (West Coast)'],
  ]) {
    assert.equal(same({ title: left }, { title: right }), null, `${left} / ${right}`);
  }
  // The title normalizer strips a trailing place; two different places are still two jobs.
  assert.equal(same(
    { title: 'Field Sales & Marketing Representative - Fridley, MN', location: 'Fridley, MN', source: 'ATS-workday' },
    { title: 'Field Sales & Marketing Representative - Minneapolis, MN', location: 'Minneapolis, MN', source: 'LinkedIn' },
  ), null);
});

test('title cleanup undoes only what feeds add', () => {
  assert.equal(sameJobTitleKey('Field Sales &amp; Marketing Representative'), sameJobTitleKey('Field Sales & Marketing Representative'));
  assert.equal(sameJobTitleKey('Territory Manager job at Henkel in US National'), sameJobTitleKey('Territory Manager'));
  assert.notEqual(sameJobTitleKey('Senior Territory Manager'), sameJobTitleKey('Territory Manager'));
});

test('two postings from one employer feed are separate requisitions', () => {
  assert.equal(same({ source: 'ATS-greenhouse' }, { source: 'ATS-lever' }), null);
  assert.equal(same({ source: 'careerforce' }, { source: 'Dejobs' }), null);
  assert.ok(same({ source: 'careerforce' }, { source: 'ATS-workday' }), 'DEjobs syndicates the employer ATS posting');
  assert.equal(employerFeedFamily('ATS-workday'), 'ats');
  assert.equal(employerFeedFamily('careerforce'), 'dejobs');
  assert.equal(employerFeedFamily('LinkedIn (Apify)'), null);
});

test('an error page is not a description', () => {
  assert.equal(isUnusableDescription(CLOUDFRONT), true);
  assert.equal(isUnusableDescription(JD), false);
  // Two unrelated jobs recovered through the same blocked proxy.
  assert.equal(same(
    { company: 'Wipaire Inc', location: 'United States', description: CLOUDFRONT, source: 'Adzuna' },
    { company: 'Duke Cannon Supply Co.', location: 'United States', description: CLOUDFRONT, source: 'Adzuna' },
  ), null);
});

test('without usable text only an exact employer, title and place match', () => {
  const short = words('store', 40);
  const identity = same(
    { source: 'LinkedIn (Apify)', company: 'Techo-Bloc', location: 'Burnsville, MN', description: short },
    { source: 'Adzuna', company: 'Techo-Bloc', location: 'Burnsville, MN', description: null },
  );
  assert.equal(identity?.rule, 'identity');
  assert.equal(same(
    { source: 'LinkedIn', company: 'Home Depot', location: 'Brooklyn Park, MN', description: short },
    { source: 'Adzuna', company: 'Home Depot', location: 'Fridley, MN', description: short },
  ), null, 'store-by-store clones');
  assert.equal(same(
    { source: 'LinkedIn', company: 'Home Depot', location: 'United States', description: null },
    { source: 'Adzuna', company: 'Home Depot', location: 'United States', description: null },
  ), null, 'a national label proves nothing');
  assert.equal(same(
    { source: 'LinkedIn', company: 'Acme', description: null },
    { source: 'Adzuna', company: 'Other Co', description: null },
  ), null, 'different employer names need text');
});

test('an anchor city is one named city', () => {
  assert.equal(sameJobAnchorCity('Minneapolis, MN'), 'minneapolis');
  assert.equal(sameJobAnchorCity('Minnesota, US'), null);
  assert.equal(sameJobAnchorCity('Remote - US'), null);
  assert.equal(sameJobAnchorCity('Atlanta, GA; Denver, CO'), null);
});
